#!/bin/zsh

ROOT_DIRECTORY="$HOME/Code/dotfiles"

echo "🚀 Setup links from $ROOT_DIRECTORY"

ln -vnfs "$ROOT_DIRECTORY" "$HOME/.dotfiles"
ln -vnfs "$ROOT_DIRECTORY/.zshrc" "$HOME/.zshrc"
ln -vnfs "$ROOT_DIRECTORY/Brewfile" "$HOME/Brewfile"
ln -vnfs "$ROOT_DIRECTORY/.warp" "$HOME/.warp"
ln -vnfs "$ROOT_DIRECTORY/starship/starship.toml" "$HOME/.config/starship.toml"
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

source ./scripts/homebrew
