#!/bin/zsh

set -euo pipefail

ROOT_DIRECTORY="${0:A:h}"

echo "🚀 Setup links from $ROOT_DIRECTORY"

ln -vnfs "$ROOT_DIRECTORY" "$HOME/.dotfiles"
ln -vnfs "$ROOT_DIRECTORY/.zshrc" "$HOME/.zshrc"
ln -vnfs "$ROOT_DIRECTORY/.zshenv" "$HOME/.zshenv"
ln -vnfs "$ROOT_DIRECTORY/Brewfile" "$HOME/Brewfile"

source "$ROOT_DIRECTORY/scripts/homebrew"
source "$ROOT_DIRECTORY/scripts/installs"

mkdir -p ~/.config
ln -vnfs "$ROOT_DIRECTORY/starship/starship.toml" ~/.config

mkdir -p ~/.config/ghostty
ln -vnfs "$ROOT_DIRECTORY/ghostty/.config" ~/.config/ghostty/config

# Pre-existing real dir (e.g. created by uv) must move aside before the symlink can land
if [[ -d ~/.config/fish && ! -L ~/.config/fish ]]; then
  mv ~/.config/fish ~/.config/fish.bak."$(date +%s)"
fi
ln -vnfs "$ROOT_DIRECTORY/fish" ~/.config/fish
