"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$git_state\
$git_status\
$nodejs\
$python\
$line_break\
$container\
$shell\
$character"""

command_timeout = 3600000

[character]
success_symbol = '[\$](bold green) '
error_symbol = '[\$](bold red) '
